projects:
  api:
    schemaPath: "src/server/api/model.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "database/__generated__/schema.graphql"
    extensions:
      prisma: database/prisma.yml